baseurl: ""

repo: "https://github.com/T-INFORMATICA"
github_user: "T-INFORMATICA"
github_repo: "t-informatica.github.io"

collections:
    courses:
        output: true
    tutorials:
        output: true

defaults:
    - scope:
          path: "_tutorials"
      values:
          layout: "tutorial"
    - scope:
          path: "_posts"
      values:
          excerpt_separator: <!--more-->
          layout: contentCentered
    - scope:
          path: "_courses/programmeren"
      values:
          course: "programmeren"
          layout: "course"
    - scope:
          path: "_courses/webontwikkeling"
      values:
          course: "webontwikkeling"
          layout: "course"
    - scope:
          path: "_courses/databanken"
      values:
          course: "databanken"
          layout: "course"
    - scope:
          path: "_courses/informatica"
      values:
          course: "informatica"
          layout: "course"
    - scope:
          path: ""
      values:
          layout: "default"
